import React,{useEffect,useMemo,useState} from 'react';
import {apiUrl} from './api.js';

const call=async(path,{token,method='GET',body}={})=>{const r=await fetch(apiUrl(path),{method,headers:{...(body?{'Content-Type':'application/json'}:{}),Authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Operacija nije uspela.');return data;};
const statusLabel={WAITING_MATERIAL:'ČEKA MATERIJAL',READY_TO_BUILD:'SPREMNO ZA IZRADU',BUILDING:'IZRADA U TOKU',REVIEW:'RMC PROVERA',APPROVED:'ODOBRENO'};
const collection=content=>content?.catalog?.services?'services':content?.catalog?.products?'products':content?.catalog?.cards?'cards':null;
const moduleName={hero:'Hero',featured:'Izdvajamo',services:'Ponuda',catalog:'Katalog',location:'Lokacija',contact:'Kontakt',booking:'Zakazivanje'};
const safeItems=items=>{const used=new Set();return items.map((item,index)=>{const fallback='item-'+(index+1);const base=(String(item?.id||fallback).replace(/[^A-Za-z0-9:_-]/g,'-').replace(/^-+|-+$/g,'')||fallback).slice(0,110);let id=base,suffix=2;while(used.has(id))id=base.slice(0,105)+'-'+suffix++;used.add(id);return {id,title:item.title||item.name||item.label||'',description:item.description||'',image:item.image||'',category:item.category||'',price:item.price??0};});};const draftFrom=project=>{const content=project.content||{},catalog=content.catalog||{},key=collection(content),editor=catalog.editorModules||{},siteEditor=content.siteConfig?.editorModules||{},form=editor.booking?.form||{};return {businessName:content.siteConfig?.business?.name||project.business?.name||'',phone:content.siteConfig?.contact?.phone||'',headline:catalog.headline||'',subtitle:catalog.subtitle||'',offerTitle:catalog.offerTitle||'',hero:catalog.hero||'',modules:{services:{kicker:editor.services?.kicker||'PONUDA',description:editor.services?.description||'Izaberite ponudu i pošaljite upit.'},booking:{kicker:editor.booking?.kicker||'',title:editor.booking?.title||'',description:editor.booking?.description||'',form:{title:form.title||'',description:form.description||'',submitLabel:form.submitLabel||'',successMessage:form.successMessage||'',fields:Array.isArray(form.fields)?form.fields:[]}},contact:{kicker:siteEditor.contact?.kicker||'KONTAKT',title:siteEditor.contact?.title||'Kontaktirajte nas',description:siteEditor.contact?.description||''}},customSections:Array.isArray(siteEditor.customSections)?siteEditor.customSections:[],items:key?safeItems(catalog[key]||[]):[]};};

export function AgentDesk({project,token,onProject,onMessage}){
 const [notes,setNotes]=useState(project.agentDesk?.notes||''),[busy,setBusy]=useState(false),[html,setHtml]=useState(''),[previewState,setPreviewState]=useState('Pripremam stvarni renderer preview…'),[stage,setStage]=useState('overview');
 const assessment=project.agentDesk?.lastAssessment;
 const draft=useMemo(()=>draftFrom(project),[project]);
 const activeModules=project.siteConfig?.modulePlan?.active||[];
 const preview=async()=>{if(!project.content){setPreviewState('Za ovaj stariji projekat nije sačuvan renderer sadržaj.');return;}setPreviewState('Osvežavam stvarni renderer preview…');try{const r=await fetch(apiUrl(`/api/admin/projects/${encodeURIComponent(project.siteId)}/preview`),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:draft})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Pregled nije dostupan.');setHtml(data.html);setPreviewState('Osnovni generički preview je spreman');}catch(error){setPreviewState(error.message);}};
 useEffect(()=>{preview();},[project.siteId]);
 const save=async(body,success)=>{setBusy(true);try{const result=await call(`/api/admin/projects/${encodeURIComponent(project.siteId)}/agent-desk`,{token,method:'PUT',body});onProject(result.project);if(body.notes!==undefined)setNotes(result.project.agentDesk?.notes||'');onMessage(success);}catch(error){onMessage(error.message)}finally{setBusy(false)}};
 const assess=async()=>{setBusy(true);try{const result=await call(`/api/admin/projects/${encodeURIComponent(project.siteId)}/agent-assess`,{token,method:'POST',body:{notes}});onProject(result.project);setNotes(result.project.agentDesk?.notes||notes);onMessage(result.assessment.agentMode==='offline'?'Agent procena je napravljena po bezbednom lokalnom pravilu; OpenAI ključ još nije podešen na serveru.':'Agent procena je osvežena.');}catch(error){onMessage(error.message)}finally{setBusy(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(assessment?.clientMessage||'');onMessage('Predlog poruke je kopiran.');}catch{onMessage('Kopiranje nije dostupno u ovom pregledaču.');}};
 const advisor=project.siteConfig?.advisorContext||{};
 const style=advisor.style||project.siteConfig?.style||'Nije odabran';
 const packageName=project.buildRequest?.request?.requestedPlan||project.requestedPlan||'Nije evidentiran';
 const businessName=project.business?.name||project.content?.siteConfig?.business?.name||'—';
 const activity=advisor.description||advisor.businessMode||advisor.businessId||'—';
 return <section className="rmc-agent-desk"><div className="rmc-agent-head"><div><p className="rmc-admin-eyebrow">RMC AGENT DESK · V48.1</p><h2>{project.business?.name}</h2><p>Site ID: <strong>{project.siteId}</strong></p></div><div className={`rmc-agent-status ${assessment?.status||'NEW'}`}>{statusLabel[assessment?.status]||'NOVI ZAHTEV'}</div></div>
  <div className="rmc-agent-steps" aria-label="Tok izrade"><button type="button" className={stage==='overview'?'active':''} onClick={()=>setStage('overview')}><b>1</b> Osnovni preview</button><button type="button" className={stage==='personalization'?'active':''} onClick={()=>setStage('personalization')}><b>2</b> Personalizacija</button><span><b>3</b> Review i finalni paket</span></div>
  <div hidden={stage!=='overview'}><section className="rmc-agent-workspace">
   <aside className="rmc-agent-record"><article><p className="rmc-admin-eyebrow">ADVISOR ZAPIS</p><h3>Trenutno stanje projekta</h3><dl className="rmc-agent-facts"><div><dt>Biznis</dt><dd>{businessName}</dd></div><div><dt>Delatnost</dt><dd>{activity}</dd></div><div><dt>Module plan</dt><dd><ul>{activeModules.map(module=><li key={module}>{moduleName[module]||module}</li>)}</ul></dd></div><div><dt>Stil</dt><dd>{style}</dd></div><div><dt>Paket iz zahteva</dt><dd>{packageName}</dd></div></dl></article></aside>
   <section className="rmc-agent-preview"><header><div><span>STVARNI RENDERER PREVIEW</span><strong>{previewState}</strong></div><button type="button" onClick={preview}>Osveži preview</button></header><div className="rmc-agent-frame">{html?<iframe title="Generički preview projekta" srcDoc={html} sandbox="allow-scripts allow-forms allow-popups"/>:<p>{previewState}</p>}</div><p className="rmc-agent-preview-note">Ovo nije novi demo: prikazuje postojeći generički sajt koji postaje osnova za personalizaciju.</p></section>  </section>
  <section className="rmc-agent-notes"><div><p className="rmc-admin-eyebrow">RMC NOTES</p><h3>Klijentove dopune i zahtevi</h3></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Unesite poruku, materijal ili poseban zahtev koji je stigao od klijenta." rows="5"/><button disabled={busy} onClick={()=>save({notes},'RMC Notes su sačuvane.')}>Sačuvaj beleške</button></section>
  <article className="rmc-agent-assessment"><header><div><h3>Agent procena</h3><p>Strukturisana interna procena; poruka se ne šalje automatski.</p></div><button disabled={busy} onClick={assess}>{busy?'Procenjujem…':'Proceni stanje projekta'}</button></header>{assessment&&<div className="rmc-agent-result"><p className={`rmc-agent-mode ${assessment.agentMode||'offline'}`}>{assessment.agentMode==='live'?'● OpenAI Agent je analizirao projekat':'● Lokalna provera — OpenAI Agent nije aktivan na serveru'}</p><p><strong>{assessment.summary}</strong></p>{assessment.missing?.length>0&&<><h4>Nedostaje</h4><ul>{assessment.missing.map((item,index)=><li key={index}>{item}</li>)}</ul></>}{assessment.recommendations?.length>0&&<><h4>Preporuke</h4><ul>{assessment.recommendations.map((item,index)=><li key={index}>{item}</li>)}</ul></>}<div className="rmc-agent-message"><h4>Predlog poruke Draganu</h4><p>{assessment.clientMessage}</p><button onClick={copy}>Kopiraj poruku</button></div><button className="rmc-agent-primary rmc-agent-next" type="button" onClick={()=>setStage('personalization')}>Nastavi na personalizaciju →</button></div>}</article></div>
  <section className="rmc-agent-personalization" hidden={stage!=='personalization'}><header><div><p className="rmc-admin-eyebrow">KORAK 2 · PERSONALIZACIJA</p><h3>Uređivanje modula</h3></div><button type="button" onClick={preview}>Osveži preview</button></header><div className="rmc-agent-personalization-grid"><aside><h4>Moduli za uređivanje</h4><ul>{activeModules.map(module=><li key={module}>{moduleName[module]||module}</li>)}<li>Lokacija / mapa</li><li>Kontakt i mreže</li><li>FAQ</li></ul></aside><section className="rmc-agent-preview"><div className="rmc-agent-frame">{html?<iframe title="Preview za personalizaciju" srcDoc={html} sandbox="allow-scripts allow-forms allow-popups"/>:<p>{previewState}</p>}</div></section></div></section>
 </section>;
}
