import React,{useEffect,useMemo,useState} from 'react';
import {apiUrl} from './api.js';
import './project-content-editor.css';

const collection=c=>c?.catalog?.services?'services':c?.catalog?.products?'products':c?.catalog?.cards?'cards':null;
const draftFrom=c=>{const x=c?.catalog||{},k=collection(c),m=x.editorModules||{},s=c?.siteConfig?.editorModules||{};return {businessName:c?.siteConfig?.business?.name||'',phone:c?.siteConfig?.contact?.phone||'',headline:x.headline||'',subtitle:x.subtitle||'',offerTitle:x.offerTitle||'',hero:x.hero||'',modules:{services:{kicker:m.services?.kicker||'PONUDA',description:m.services?.description||'Izaberite uslugu i pošaljite zahtev ili nas kontaktirajte.'},booking:{kicker:m.booking?.kicker||'',title:m.booking?.title||'',description:m.booking?.description||''},contact:{kicker:s.contact?.kicker||'KONTAKT',title:s.contact?.title||'Kontaktirajte nas',description:s.contact?.description||''}},customSections:s.customSections||[],items:(k?x[k]:[]).map(i=>({id:i.id,title:i.title||i.name||i.label||'',description:i.description||'',image:i.image||'',category:i.category||'',price:i.price??''}))};};
function Field({label,value,onChange,rows=1,type='text'}){return <label className="rmc-content-field"><span>{label}</span>{rows>1?<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}

export function ProjectContentEditor({project,token,onSaved,onMessage}){
 const [draft,setDraft]=useState(()=>draftFrom(project.content)),[busy,setBusy]=useState(false),[html,setHtml]=useState(''),[previewState,setPreviewState]=useState('Učitavam pregled…'),[active,setActive]=useState('hero');
 const key=collection(project.content),label=key==='services'?'usluge':key==='products'?'proizvodi':'stavke ponude';
 const sections=useMemo(()=>[{id:'business',label:'Osnovno'},{id:'hero',label:'Hero'},{id:'items',label:key==='products'?'Proizvodi':key==='services'?'Usluge':'Ponuda'},{id:'booking',label:'Zakazivanje',hidden:!project.capabilities.booking},{id:'contact',label:'Kontakt'},{id:'custom',label:'Novi blokovi'}].filter(s=>!s.hidden),[key,project.capabilities.booking]);
 const update=(name,value)=>setDraft(p=>({...p,[name]:value}));
 const item=(index,name,value)=>setDraft(p=>({...p,items:p.items.map((v,i)=>i===index?{...v,[name]:value}:v)}));
 const module=(group,name,value)=>setDraft(p=>({...p,modules:{...p.modules,[group]:{...p.modules[group],[name]:value}}}));
 const custom=(index,name,value)=>setDraft(p=>({...p,customSections:p.customSections.map((v,i)=>i===index?{...v,[name]:value}:v)}));
 const addCustom=()=>setDraft(p=>({...p,customSections:[...p.customSections,{id:`custom-${Date.now()}`,kicker:'VIŠE INFORMACIJA',title:'Novi sadržajni blok',body:'Unesite tekst koji želite da prikažete.',linkLabel:'',linkHref:''}]}));
 const removeCustom=index=>setDraft(p=>({...p,customSections:p.customSections.filter((_,i)=>i!==index)}));
 const remove=index=>setDraft(p=>p.items.length<2?p:{...p,items:p.items.filter((_,i)=>i!==index)});
 const add=()=>setDraft(p=>{const n=p.items.length+1;return {...p,items:[...p.items,{id:`editor-${Date.now()}-${n}`,title:key==='products'?'Novi proizvod':'Nova usluga',description:'',image:'',category:key==='products'?'Ponuda':'',price:key==='products'?0:''}]};});
 const preview=async(content=draft)=>{setPreviewState('Osvežavam stvarni prikaz…');try{const r=await fetch(apiUrl('/api/admin/projects/'+encodeURIComponent(project.siteId)+'/preview'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Pregled nije dostupan.');setHtml(data.html);setPreviewState('Pregled je ažuran');}catch(e){setPreviewState(e.message)}};
 useEffect(()=>{preview();},[]);useEffect(()=>{const t=setTimeout(()=>preview(),700);return()=>clearTimeout(t);},[draft]);
 const publish=async()=>{setBusy(true);onMessage('');try{const r=await fetch(apiUrl('/api/admin/projects/'+encodeURIComponent(project.siteId)+'/export'),{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'Publish ZIP nije moguće pripremiti.');}const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rmc-publish-sajt.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);onMessage('Publish ZIP je preuzet. Ne sadrži kod niti aktivira Portal.');}catch(e){onMessage(e.message)}finally{setBusy(false)}};
 const submit=async e=>{e.preventDefault();setBusy(true);onMessage('');try{const r=await fetch(apiUrl('/api/admin/projects/'+encodeURIComponent(project.siteId)+'/content'),{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:draft})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Sadržaj nije sačuvan.');onSaved(data.project);onMessage('Sadržaj je sačuvan. Sledeći ZIP koristi ove izmene.');preview(draft);}catch(x){onMessage(x.message)}finally{setBusy(false)}};
 if(!project.content)return <section className="rmc-content-editor"><p>Ovaj stariji projekat nema sadržaj za uređivanje. Generišite novi projekat iz Advisora.</p></section>;
 return <form className="rmc-editor-workspace" onSubmit={submit}>
  <aside className="rmc-editor-nav"><div className="rmc-editor-nav-title"><span>RMC EDITOR</span><strong>{project.business.name}</strong><small>Project ID · {project.siteId}</small></div><nav aria-label="Sekcije za uređivanje">{sections.map(s=><button key={s.id} type="button" onClick={()=>setActive(s.id)} className={active===s.id?'active':''}>{s.label}</button>)}</nav><div className="rmc-editor-photo-note"><strong>Fotografije</strong><p>Ubacivanje fotografije u ZIP uvodimo preko privremene biblioteke; Render disk ne bi čuvao fajl pouzdano.</p></div></aside>
  <main className="rmc-editor-canvas"><header><div><span>ŽIVI PREGLED</span><strong>{previewState}</strong></div><button type="button" onClick={()=>preview()} className="rmc-editor-plain">Osveži</button></header><div className="rmc-editor-frame"><iframe title="Pregled objavljenog sajta" srcDoc={html} sandbox="allow-scripts allow-forms allow-popups"/></div></main>
  <aside className="rmc-editor-inspector"><header><div><span>UREĐIVANJE</span><h2>{sections.find(s=>s.id===active)?.label}</h2></div><div className="rmc-editor-actions"><button disabled={busy} className="rmc-content-save">{busy?'Čuvam…':'Sačuvaj'}</button><button type="button" disabled={busy} className="rmc-content-publish" onClick={publish}>Publish ZIP</button></div></header>
   {active==='business'&&<section className="rmc-inspector-body"><p>Podaci u zaglavlju i kontakt delu sajta.</p><Field label="Naziv firme" value={draft.businessName} onChange={v=>update('businessName',v)}/><Field label="Telefon" value={draft.phone} onChange={v=>update('phone',v)}/></section>}
   {active==='hero'&&<section className="rmc-inspector-body"><p>Ovo je kompletan Hero blok.</p><Field label="Naslov" value={draft.headline} onChange={v=>update('headline',v)}/><Field label="Opis hero sekcije" value={draft.subtitle} rows={4} onChange={v=>update('subtitle',v)}/><div className="rmc-photo-placeholder"><strong>Fotografija hero sekcije</strong><p>„Ubaci fotografiju” dolazi zajedno sa privremenim storage-om i automatskim unosom u Publish ZIP.</p></div></section>}
   {active==='items'&&<section className="rmc-inspector-body"><p>Kompletan blok {label}: naslov, uvod i sve kartice.</p><Field label="Oznaka iznad naslova" value={draft.modules.services.kicker} onChange={v=>module('services','kicker',v)}/><Field label={`Naslov bloka ${label}`} value={draft.offerTitle} onChange={v=>update('offerTitle',v)}/><Field label="Uvodni tekst bloka" value={draft.modules.services.description} rows={3} onChange={v=>module('services','description',v)}/><div className="rmc-content-items">{draft.items.map((entry,index)=><article className="rmc-content-item" key={entry.id||index}><header><strong>{label.slice(0,-1)} {index+1}</strong>{draft.items.length>1&&<button type="button" className="rmc-content-delete" onClick={()=>remove(index)}>Ukloni</button>}</header><Field label="Naziv" value={entry.title} onChange={v=>item(index,'title',v)}/>{key==='products'&&<Field label="Cena (RSD)" type="number" value={entry.price} onChange={v=>item(index,'price',v)}/>}<Field label="Opis" value={entry.description} rows={3} onChange={v=>item(index,'description',v)}/>{key==='products'&&<Field label="Kategorija" value={entry.category} onChange={v=>item(index,'category',v)}/>}<div className="rmc-photo-placeholder compact"><strong>Fotografija stavke</strong><p>Dodaćemo je kroz biblioteku fotografija.</p></div></article>)}</div>{(key==='products'||key==='services')&&<button type="button" className="rmc-content-add" onClick={add}>Dodaj {key==='products'?'proizvod':'uslugu'}</button>}</section>}
   {active==='booking'&&<section className="rmc-inspector-body"><p>Menja se samo sadržaj modula. Forma, usluge i slanje ostaju povezani sa Business paketom.</p><Field label="Oznaka bloka" value={draft.modules.booking.kicker} onChange={v=>module('booking','kicker',v)}/><Field label="Naslov bloka" value={draft.modules.booking.title} onChange={v=>module('booking','title',v)}/><Field label="Opis bloka" value={draft.modules.booking.description} rows={4} onChange={v=>module('booking','description',v)}/></section>}
   {active==='contact'&&<section className="rmc-inspector-body"><p>Kompletan kontakt blok. Dugme telefona ostaje vezano za broj iz „Osnovno”.</p><Field label="Oznaka bloka" value={draft.modules.contact.kicker} onChange={v=>module('contact','kicker',v)}/><Field label="Naslov bloka" value={draft.modules.contact.title} onChange={v=>module('contact','title',v)}/><Field label="Opis bloka" value={draft.modules.contact.description} rows={4} onChange={v=>module('contact','description',v)}/></section>}
   {active==='custom'&&<section className="rmc-inspector-body"><p>Novi blokovi se prikazuju jedan ispod drugog, neposredno pre kontakta.</p><div className="rmc-content-items">{draft.customSections.map((entry,index)=><article className="rmc-content-item" key={entry.id||index}><header><strong>Blok {index+1}</strong><button type="button" className="rmc-content-delete" onClick={()=>removeCustom(index)}>Ukloni</button></header><Field label="Oznaka" value={entry.kicker} onChange={v=>custom(index,'kicker',v)}/><Field label="Naslov" value={entry.title} onChange={v=>custom(index,'title',v)}/><Field label="Tekst" value={entry.body} rows={4} onChange={v=>custom(index,'body',v)}/><Field label="Tekst linka (opciono)" value={entry.linkLabel} onChange={v=>custom(index,'linkLabel',v)}/><Field label="Odredište linka" value={entry.linkHref} onChange={v=>custom(index,'linkHref',v)}/></article>)}</div><button type="button" className="rmc-content-add" onClick={addCustom}>Dodaj novi sadržajni blok</button></section>}
  </aside>
 </form>;
}
