import React,{useState} from 'react';
import {apiUrl} from './api.js';
import './project-content-editor.css';

const collection=content=>content?.catalog?.services?'services':content?.catalog?.products?'products':content?.catalog?.cards?'cards':null;
const draftFrom=content=>{const catalog=content?.catalog||{},key=collection(content);return {businessName:content?.siteConfig?.business?.name||'',phone:content?.siteConfig?.contact?.phone||'',headline:catalog.headline||'',subtitle:catalog.subtitle||'',offerTitle:catalog.offerTitle||'',hero:catalog.hero||'',items:(key?catalog[key]:[]).map(item=>({id:item.id,title:item.title||item.name||item.label||'',description:item.description||'',image:item.image||'',category:item.category||'',price:item.price??''}))};};
function Field({label,value,onChange,rows=1,type='text',hint}){return <label className="rmc-content-field"><span>{label}</span>{rows>1?<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>} {hint&&<small>{hint}</small>}</label>}

export function ProjectContentEditor({project,token,onSaved,onMessage}){
 const [draft,setDraft]=useState(()=>draftFrom(project.content));const [busy,setBusy]=useState(false);
 const key=collection(project.content),label=key==='services'?'usluge':key==='products'?'proizvodi':'stavke ponude';
 const update=(name,value)=>setDraft(previous=>({...previous,[name]:value}));
 const item=(index,name,value)=>setDraft(previous=>({...previous,items:previous.items.map((current,i)=>i===index?{...current,[name]:value}:current)}));
 const remove=index=>setDraft(previous=>previous.items.length<2?previous:{...previous,items:previous.items.filter((_,i)=>i!==index)});
 const add=()=>setDraft(previous=>{const next=previous.items.length+1;return {...previous,items:[...previous.items,{id:`editor-${Date.now()}-${next}`,title:key==='products'?'Novi proizvod':'Nova usluga',description:'',image:'',category:key==='products'?'Ponuda':'',price:key==='products'?0:''}]};});
 const publish=async()=>{setBusy(true);onMessage('');try{const response=await fetch(apiUrl('/api/admin/projects/'+encodeURIComponent(project.siteId)+'/export'),{method:'POST',headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Publish ZIP nije moguće pripremiti.');}const blob=await response.blob(),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='rmc-publish-sajt.zip';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);onMessage('Publish ZIP je preuzet. Ne sadrži kod niti aktivira Portal.');}catch(error){onMessage(error.message)}finally{setBusy(false)}};
 const submit=async event=>{event.preventDefault();setBusy(true);onMessage('');try{const response=await fetch(apiUrl('/api/admin/projects/'+encodeURIComponent(project.siteId)+'/content'),{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:draft})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Sadržaj nije sačuvan.');onSaved(data.project);onMessage('Sadržaj je sačuvan. Sledeći ZIP koristi ove izmene.');}catch(error){onMessage(error.message)}finally{setBusy(false)}};
 if(!project.content)return <section className="rmc-content-editor"><p className="rmc-admin-eyebrow">SADRŽAJ SAJTA</p><p>Ovaj stariji projekat nema sačuvan sadržaj za uređivanje. Generišite novi projekat iz Advisora.</p></section>;
 return <form className="rmc-content-editor" onSubmit={submit}><p className="rmc-admin-eyebrow">SADRŽAJ SAJTA</p><h2>Uredite pre Publish ZIP-a</h2><p>Izmene ostaju vezane za isti Project ID. Paket, API veza i Portal prava se ne menjaju ovde.</p><section><p className="rmc-admin-eyebrow">OSNOVNI PODACI</p><div className="rmc-content-grid"><Field label="Naziv firme" value={draft.businessName} onChange={value=>update('businessName',value)}/><Field label="Telefon" value={draft.phone} onChange={value=>update('phone',value)}/></div></section><section><p className="rmc-admin-eyebrow">HERO</p><div className="rmc-content-grid"><Field label="Naslov" value={draft.headline} onChange={value=>update('headline',value)}/><Field label="Naslov sekcije ponude" value={draft.offerTitle} onChange={value=>update('offerTitle',value)}/><Field label="Opis" value={draft.subtitle} rows={3} onChange={value=>update('subtitle',value)}/><Field label="Putanja hero slike" value={draft.hero} onChange={value=>update('hero',value)} hint="Za sada: assets/... slika koja se nalazi u ZIP-u."/></div></section>{key&&<section><p className="rmc-admin-eyebrow">MODUL — {label.toUpperCase()}</p><p className="rmc-content-help">Kartice menjaju stvarni sadržaj sajta. Možete dodati ili ukloniti stavku; najmanje jedna mora ostati.</p><div className="rmc-content-items">{draft.items.map((entry,index)=><article className="rmc-content-item" key={entry.id||index}><header><strong>{label.slice(0,-1)} {index+1}</strong>{draft.items.length>1&&<button type="button" className="rmc-content-delete" onClick={()=>remove(index)}>Ukloni</button>}</header><div className="rmc-content-grid"><Field label="Naziv" value={entry.title} onChange={value=>item(index,'title',value)}/>{key==='products'&&<Field label="Cena (RSD)" type="number" value={entry.price} onChange={value=>item(index,'price',value)}/>}<Field label="Opis" value={entry.description} rows={3} onChange={value=>item(index,'description',value)}/><Field label="Putanja slike" value={entry.image} onChange={value=>item(index,'image',value)}/>{key==='products'&&<Field label="Kategorija" value={entry.category} onChange={value=>item(index,'category',value)}/>}</div></article>)}</div>{(key==='products'||key==='services')&&<button type="button" className="rmc-content-add" onClick={add}>Dodaj {key==='products'?'proizvod':'uslugu'}</button>}</section>}<div className="rmc-content-actions"><button disabled={busy} className="rmc-content-save">{busy?'Čuvam…':'Sačuvaj sadržaj projekta'}</button><button type="button" disabled={busy} className="rmc-content-publish" onClick={publish}>Preuzmi Publish ZIP</button></div></form>;
}
