import test from 'node:test';import assert from 'node:assert/strict';
import {STATUS,makeProfile,normalizeRequest,slotCheck,alternatives,addDays,weekStart,isDate,weekdayIndex,toMin,fromMin,validateImport,icsFor,dateKey,clone,dayPartLabel} from '../booking-core.mjs';
function fixture(){const p=makeProfile('Test');p.services=[{id:'hair',name:'Šišanje',duration:30,units:1},{id:'color',name:'Farbanje',duration:90,units:1}];p.hours=Array.from({length:7},()=>({enabled:true,start:'09:00',end:'17:00'}));return p;}
function book(p,values={}){return {...normalizeRequest({serviceId:'hair',date:'2026-09-28',time:'10:00',clientName:'Test klijent',...values},p),status:STATUS.CONFIRMED};}
test('date strict validation and local date movement',()=>{assert.equal(isDate('2026-02-29'),false);assert.equal(isDate('2024-02-29'),true);assert.equal(addDays('2026-12-31',1),'2027-01-01');assert.equal(weekStart('2026-09-30'),'2026-09-28');assert.equal(weekdayIndex('2026-09-28'),0);assert.equal(fromMin(toMin('14:45')),'14:45');});
test('manual request remains pending and retains snapshot duration',()=>{const p=fixture();const b=normalizeRequest({serviceId:'hair',date:'2026-09-28',time:'10:00',clientName:'Test',source:'manual'},p);p.services[0].duration=60;assert.equal(b.duration,30);assert.equal(b.status,STATUS.PENDING);});
test('invalid request rejected',()=>{const p=fixture();assert.throws(()=>normalizeRequest({serviceId:'?',date:'2026-09-28',time:'10:00',clientName:'Test'},p));assert.throws(()=>normalizeRequest({serviceId:'hair',date:'2026-02-31',time:'10:00',clientName:'Test'},p));assert.throws(()=>normalizeRequest({serviceId:'hair',date:'2026-09-28',time:'10:00',clientName:'X'},p));});
test('pending request must not block a slot',()=>{const p=fixture(),b=book(p);b.status=STATUS.PENDING;assert.equal(slotCheck(p,[b],{date:b.date,time:b.time,duration:30}).ok,true);});
test('confirmed slot blocks identical time',()=>{const p=fixture(),b=book(p);const res=slotCheck(p,[b],{date:b.date,time:b.time,duration:30});assert.equal(res.ok,false);assert.match(res.reason,/zauzet/);});
test('next immediate slot remains available with zero buffer',()=>{const p=fixture(),b=book(p);assert.equal(slotCheck(p,[b],{date:b.date,time:'10:30',duration:30}).ok,true);});
test('buffer blocks back-to-back slot then frees it',()=>{const p=fixture(),b=book(p);p.buffer=10;assert.equal(slotCheck(p,[b],{date:b.date,time:'10:30',duration:30}).ok,false);assert.equal(slotCheck(p,[b],{date:b.date,time:'10:40',duration:30}).ok,true);});
test('crossing working hours is rejected',()=>{const p=fixture();assert.match(slotCheck(p,[],{date:'2026-09-28',time:'16:45',duration:30}).reason,/radnog/);});
test('closed weekday and specific closed date rejected',()=>{const p=fixture();p.hours[0].enabled=false;assert.match(slotCheck(p,[],{date:'2026-09-28',time:'10:00',duration:30}).reason,/Zatvoreno/);p.hours[0].enabled=true;p.closedDates=['2026-09-28'];assert.match(slotCheck(p,[],{date:'2026-09-28',time:'10:00',duration:30}).reason,/Neradni/);});
test('midday break rejected, adjacent end permitted',()=>{const p=fixture();p.breaks={enabled:true,start:'12:00',end:'12:30'};assert.equal(slotCheck(p,[],{date:'2026-09-28',time:'11:45',duration:30}).ok,false);assert.equal(slotCheck(p,[],{date:'2026-09-28',time:'12:30',duration:30}).ok,true);});
test('exclude booking itself during confirmation and proposed acceptance',()=>{const p=fixture(),b=book(p);assert.equal(slotCheck(p,[b],{date:b.date,time:b.time,duration:30,excludeId:b.id}).ok,true);});
test('multi-resource occupancy catches partial overlap',()=>{const p=fixture();p.capacity=3;const b1=book(p,{time:'10:00'}),b2=book(p,{time:'10:15'});b1.units=2;b2.units=1;assert.equal(slotCheck(p,[b1,b2],{date:b1.date,time:'10:20',duration:10,units:1}).ok,false);assert.equal(slotCheck(p,[b1],{date:b1.date,time:'10:00',duration:30,units:1}).ok,true);});
test('alternatives skip busy and prefer same day',()=>{const p=fixture(),b=book(p);const alt=alternatives(p,[b],{date:b.date,time:b.time,duration:30,units:1,id:'fresh'},4,3);assert.deepEqual(alt[0],{date:'2026-09-28',time:'10:30'});assert.equal(alt.length,4);});
test('alternatives skip a closed day',()=>{const p=fixture();p.closedDates=['2026-09-28'];const alt=alternatives(p,[],{date:'2026-09-28',time:'16:45',duration:30,units:1},2,3);assert.equal(alt[0].date,'2026-09-29');});
test('alternatives empty when requested service requires more capacity',()=>{const p=fixture();assert.deepEqual(alternatives(p,[],{date:'2026-09-28',time:'10:00',duration:30,units:2},4,1),[]);});
test('backup rejects malformed data',()=>{assert.throws(()=>validateImport({schema:99,profiles:[],bookings:[]}));const p=fixture();const valid={schema:1,activeProfileId:p.id,profiles:[p],bookings:[book(p)]};assert.equal(validateImport(valid).bookings.length,1);const bad=clone(valid);bad.bookings[0].date='2026-02-30';assert.throws(()=>validateImport(bad));});
test('ics export includes correct event and rejects unconfirmed',()=>{const p=fixture(),b=book(p);const ics=icsFor(p,b);assert.match(ics,/BEGIN:VEVENT/);assert.match(ics,/DTSTART:20260928T100000/);assert.match(ics,/DTEND:20260928T103000/);b.status=STATUS.PENDING;assert.throws(()=>icsFor(p,b));});
test('overlapping proposed slots never block unless confirmed',()=>{const p=fixture(),b=book(p);b.status=STATUS.PROPOSED;b.proposal={date:b.date,time:b.time};assert.equal(slotCheck(p,[b],{date:b.date,time:b.time,duration:30}).ok,true);});

test('DAY_PART request remains unscheduled until a concrete proposal is confirmed',()=>{
 const p=fixture();const b=normalizeRequest({serviceId:'hair',date:'2026-09-28',timingMode:'DAY_PART',dayPart:'MORNING',clientName:'Test klijent'},p);
 assert.equal(b.time,'');assert.equal(b.dayPart,'MORNING');assert.equal(b.status,STATUS.PENDING);assert.equal(dayPartLabel(b.dayPart),'Pre podne');
 assert.equal(slotCheck(p,[],{date:b.date,time:b.time,duration:b.duration}).ok,false);
 b.proposal={date:b.date,time:'10:00'};b.time=b.proposal.time;b.timingMode='EXACT_TIME';b.dayPart='';b.status=STATUS.CONFIRMED;
 assert.equal(slotCheck(p,[b],{date:b.date,time:'10:00',duration:b.duration}).ok,false);
});
