import {renderServiceHtml} from './render-service.js';
// Single renderer shared by in-app preview and standalone ZIP export.
// Business decisions are already resolved by Advisor; this module only renders.
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const money=n=>`${new Intl.NumberFormat('sr-RS',{maximumFractionDigits:0}).format(n)} RSD`;
const safeJson=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026').replace(/\u2028/g,'\\u2028');

export function renderHtml({siteConfig:site,catalog}){
  if(site?.capabilities?.serviceProfile)return renderServiceHtml({siteConfig:site,catalog});
  if(!site?.business?.name || !catalog?.products?.length)throw new Error('Nepotpuna konfiguracija sajta.');
  const wine=site.capabilities.wineTastings;
  const butcher=site.business.id==='butcher-shop';
  const inquiryLabel=site.business.id==='shoe-shop'?'Proveri dostupnost':site.business.id==='auto-parts'?'Zatraži potvrdu dostupnosti':site.business.id==='phone-store'?'Proveri dostupnost':'Pošalji upit';
  const asset=s=>esc(s);
  const itemCard=p=>`<article class="shop-card" data-card data-category="${esc(p.category)}" data-search="${esc(`${p.title} ${p.category}`.toLowerCase())}">
    <button class="product-image" type="button" data-product="${esc(p.id)}" aria-label="Detalji: ${esc(p.title)}"><img src="${asset(p.image)}" loading="lazy" alt="${esc(p.title)}"></button>
    <div class="shop-card-body"><small>${esc(p.category)}</small><h3>${esc(p.title)}</h3><strong>${money(p.price)}${p.unit==='kg'?'/kg':''}</strong><button type="button" data-product="${esc(p.id)}" class="secondary">${site.capabilities.commerce?'Detalji i poručivanje →':'Detalji →'}</button></div>
  </article>`;
  const categories=[...new Set(catalog.products.map(x=>x.category))];
  const tastingSection=wine?`<section class="site-section tasting" id="degustacije"><div class="tasting-photo"><img src="${asset(catalog.tastingImage)}" loading="lazy" alt="Vođena degustacija vina"></div><div class="tasting-copy"><div class="kicker">DOŽIVLJAJ</div><h2>Degustacije vina</h2><p>Vođena degustacija uz pažljivo odabrana vina. Pošaljite željeni datum i broj osoba, a vinoteka će potvrditi mogućnosti.</p>
  <form id="tastingForm" class="booking-form"><label>Vrsta degustacije<select name="experience" required><option value="Vođena degustacija">Vođena degustacija</option><option value="Tematska degustacija">Tematska degustacija</option><option value="Privatna degustacija">Privatna degustacija</option></select></label>
  <label>Datum<input type="date" name="date" required></label><label>Željeno vreme<input type="time" name="time" required></label><label>Broj osoba<input type="number" name="partySize" min="1" max="30" value="2" required></label>
  <label>Ime<input name="name" maxlength="90" required autocomplete="name"></label><label>Telefon<input name="phone" type="tel" required maxlength="35" autocomplete="tel"></label>
  <label class="wide">Napomena (opciono)<textarea name="note" maxlength="400" rows="2"></textarea></label><button class="primary wide" type="submit">Pripremi zahtev za degustaciju</button></form><p class="hint">Termin nije potvrđen dok vam vinoteka ne odgovori.</p></div></section>`:'';
  const heroCTA=butcher && site.capabilities.butcherGrillService && site.capabilities.commerce?'Poručite meso za pripremu':'Pogledajte proizvode';
  const featured=catalog.products.slice(0,3).map(itemCard).join('');
  // Ship only presentation data needed by the standalone site, never full Advisor state.
  const publicSite={business:{id:site.business.id,name:site.business.name},
    capabilities:{commerce:!!site.capabilities.commerce,butcherGrillService:!!site.capabilities.butcherGrillService,wineTastings:!!site.capabilities.wineTastings,
      variantNote:!!site.capabilities.variantNote,variantLabel:site.capabilities.variantLabel||'Varijanta / napomena',requireVehicle:!!site.capabilities.requireVehicle},
    contact:{phone:site.contact.phone||''}};
  const data=safeJson({siteConfig:publicSite,catalog});
  return `<!doctype html><html lang="sr" data-style="${esc(site.style)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#14253b"><title>${esc(site.business.name)} | Ponuda</title><meta name="description" content="${esc(catalog.subtitle)}"><link rel="stylesheet" href="site.css"></head><body>
  <header class="site-header"><div class="brandmark" aria-label="${esc(site.business.name)}"><span class="monogram">${esc(site.business.name.trim().slice(0,2).toUpperCase())}</span><span>${esc(site.business.name)}</span></div><nav aria-label="Glavna navigacija"><a href="#ponuda">Ponuda</a>${wine?'<a href="#degustacije">Degustacije</a>':''}<a href="#kontakt">Kontakt</a></nav><a class="header-cta" href="${wine?'#degustacije':'#ponuda'}">${wine?'Zakaži degustaciju':'Pogledaj ponudu'}</a></header>
  <main><section class="hero" style="--hero-image:url('${asset(catalog.hero)}')"><div class="hero-content"><h1>${esc(catalog.headline)}</h1><p>${esc(catalog.subtitle)}</p><div class="hero-actions"><a class="primary" href="#ponuda">${esc(heroCTA)}</a>${wine?'<a class="outline-light" href="#degustacije">Zakaži degustaciju</a>':''}</div></div></section>
  <section class="site-section featured" id="izdvajamo"><div class="section-heading"><div><div class="kicker">IZDVAJAMO</div><h2>Naša preporuka</h2><p>Izbor iz aktuelnog kataloga.</p></div><a class="text-link" href="#ponuda">Svi proizvodi ↗</a></div><div class="card-grid">${featured}</div>${wine?'<a class="featured-experience" href="#degustacije">Vođena degustacija vina <span>Pronađi termin →</span></a>':''}</section>
  <section class="site-section" id="ponuda"><div class="section-heading"><div><div class="kicker">PONUDA</div><h2>${esc(catalog.offerTitle|| (butcher?'Dnevna ponuda':wine?'Izdvojena vina':'Pronađite svoj par'))}</h2><p>Demo cene služe za proveru korpe; zamenite ih stvarnim cenama pre objave.</p></div></div><div class="catalog-controls"><label class="search-label">Pretražite proizvode<input id="catalogSearch" type="search" placeholder="Naziv ili kategorija" aria-label="Pretražite proizvode"></label><div class="chips" role="group" aria-label="Kategorije"><button class="chip is-active" type="button" data-filter="Sve" aria-pressed="true">Sve</button>${categories.map(c=>`<button class="chip" type="button" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div></div><p class="count-note" id="catalogCount">Prikazano: ${catalog.products.length}</p><div class="card-grid" id="catalogGrid">${catalog.products.map(itemCard).join('')}</div></section>
  ${tastingSection}
  <section class="site-section contact" id="kontakt"><div class="kicker">KONTAKT</div><h2>Čujemo se!</h2><p>${site.capabilities.commerce?'Izaberite proizvode ili pošaljite upit. Porudžbine se šalju prodavnici na potvrdu.':'Pogledajte našu ponudu i kontaktirajte nas za dodatne informacije.'}</p>${site.contact.phone?`<a class="primary" href="tel:${esc(site.contact.phone.replace(/[^+\d]/g,''))}">Pozovite nas</a>`:'<p class="hint">Unesite pravi telefon pre objavljivanja sajta.</p>'}</section></main>
  <footer class="site-footer"><strong>${esc(site.business.name)}</strong><span>Demo sajt · Kreirano pomoću RMC Web Solutions</span></footer>
  <button id="stickyCart" class="sticky-cart" type="button" hidden><span>🛒 <span id="stickyCount">0 artikala</span></span><strong id="stickyTotal">0 RSD</strong><span class="sticky-arrow">Pregledaj →</span></button>
  <dialog id="productDialog" class="site-dialog product-dialog" aria-label="Detalji proizvoda"><button type="button" class="dialog-close" data-close aria-label="Zatvori">×</button><div class="product-detail-grid"><img id="detailImage" alt=""><div class="detail-body"><div class="kicker" id="detailCategory"></div><h2 id="detailName"></h2><p class="detail-price" id="detailPrice"></p><details><summary>Više detalja</summary><p>Ponuda je demonstraciona. Dostupnost i cena potvrđuju se prilikom naručivanja.</p></details><label id="prepWrap" hidden>Način pripreme<select id="preparation"><option value="Sveže">Sirovo / sveže</option><option value="Grilovano">Grilovano</option></select></label><label id="variantWrap" hidden><span id="variantLabel">Varijanta / napomena</span><input id="variantInput" type="text" maxlength="110" placeholder="Unesite željenu varijantu"></label><label id="sizeWrap" hidden>Veličina<select id="shoeSize"><option value="36">36</option><option value="37">37</option><option value="38">38</option><option value="39">39</option><option value="40">40</option><option value="41">41</option><option value="42">42</option><option value="43">43</option><option value="44">44</option><option value="45">45</option></select></label><div class="detail-buy"><label>Količina<div class="stepper"><button type="button" id="qtyMinus" aria-label="Smanji količinu">−</button><input id="qtyInput" type="number" min="1" max="99" value="1" aria-label="Količina"><button type="button" id="qtyPlus" aria-label="Povećaj količinu">+</button></div></label><p id="detailSubtotal" class="detail-subtotal"></p></div><div class="detail-actions">${site.capabilities.commerce?`<button class="primary" type="button" id="addToCart">Dodaj u korpu</button><button class="secondary" type="button" id="buyNow">Poruči sada</button>${site.business.id==='auto-parts'||site.business.id==='phone-store'?`<button class="secondary" type="button" id="availabilityInquiry">${inquiryLabel}</button>`:''}`:`<button class="primary" type="button" id="availabilityInquiry">${inquiryLabel}</button>`}</div></div></div></dialog>
  <dialog id="cartDialog" class="site-dialog cart-dialog" aria-label="Vaša korpa"><button type="button" class="dialog-close" data-close aria-label="Zatvori">×</button><div class="dialog-pad"><div class="kicker">KORPA</div><h2>Vaš izbor</h2><div id="cartLines"></div><div class="cart-total">Ukupno: <strong id="cartTotal">0 RSD</strong></div><div class="dialog-actions"><button class="primary" id="orderFromCart" type="button">Poruči korpu</button><button class="secondary" id="clearCart" type="button">Očisti</button></div></div></dialog>
  <dialog id="orderDialog" class="site-dialog order-dialog" aria-label="Zahtev za porudžbinu"><button type="button" class="dialog-close" data-close aria-label="Zatvori">×</button><div class="dialog-pad"><div class="kicker" id="orderKicker">PORUDŽBINA</div><h2 id="orderHeading">Proverite i pošaljite zahtev</h2><form id="orderForm"><label>Ime<input required name="name" maxlength="90" autocomplete="name"></label><label>Telefon<input required name="phone" type="tel" maxlength="35" autocomplete="tel"></label><label id="fulfillmentWrap">Način preuzimanja<select name="fulfillment"><option>Preuzimanje u radnji</option><option>Po dogovoru sa prodavnicom</option></select></label><label>Napomena<textarea name="note" rows="2" maxlength="400"></textarea></label><button class="primary" type="submit" id="orderSubmit">Pripremi poruku</button></form><div id="sharePanel" hidden><p>Poruka je spremna. Izaberite kako je želite poslati.</p><pre id="orderMessage"></pre><div class="dialog-actions"><button class="primary" type="button" id="copyMessage">Kopiraj poruku</button><a id="viberMessage" class="secondary" target="_blank" rel="noopener noreferrer">Viber</a><a id="waMessage" class="secondary" target="_blank" rel="noopener noreferrer">WhatsApp</a></div><p class="hint">Viber podržava do 200 znakova u deljenoj poruci. Za ceo zahtev upotrebite „Kopiraj poruku“ i nalepite ga u Viber ako je potrebno.</p><p id="copyStatus" role="status"></p></div><p class="hint">Nema automatske naplate ni potvrde dostupnosti.</p></div></dialog>
  <dialog id="bookingDialog" class="site-dialog booking-dialog" aria-label="Zahtev za degustaciju"><button type="button" class="dialog-close" data-close aria-label="Zatvori">×</button><div class="dialog-pad"><div class="kicker">DEGUSTACIJA</div><h2>Zahtev je spreman</h2><pre id="bookingMessage"></pre><div class="dialog-actions"><button class="primary" type="button" id="copyBooking">Kopiraj zahtev</button><a class="secondary" id="viberBooking" target="_blank" rel="noopener noreferrer">Viber</a><a class="secondary" id="waBooking" target="_blank" rel="noopener noreferrer">WhatsApp</a></div><p class="hint">Viber podržava do 200 znakova; za kompletnu poruku koristite kopiranje. Termin se potvrđuje tek nakon odgovora.</p></div></dialog>
  <script id="siteData" type="application/json">${data}</script><script src="export-runtime.js" defer></script></body></html>`;
}
